# Generated by Django 5.2.7 on 2026-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Logo URL'),
        ),
    ]
