# Generated by Django 5.2.7 on 2026-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_location_lat_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='hours_saturday',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Horario Sábado'),
        ),
        migrations.AddField(
            model_name='location',
            name='hours_sunday',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Horario Domingo'),
        ),
        migrations.AddField(
            model_name='location',
            name='hours_weekdays',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Horario L-V'),
        ),
    ]
