# Generated by Django 5.2.7 on 2026-05-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_location_hours_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='hours_weekdays',
        ),
        migrations.AddField(
            model_name='location',
            name='hours_weekday',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Horario L-V'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hours_saturday',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Horario Sábado'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hours_sunday',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Horario Domingo'),
        ),
    ]
