# Generated by Django 5.2.7 on 2026-06-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_add_location_hours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productstock',
            name='chk_product_stock_qty_nonneg',
        ),
        migrations.AlterField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(default=0, editable=False, verbose_name='Stock total'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad disponible'),
        ),
    ]
