# Generated by Django 5.2.7 on 2026-07-22 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_tracking_invoice_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas del pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wompi_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referencia Wompi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID de transacción Wompi'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('preparing', 'En preparación'), ('shipping', 'En camino'), ('delivered', 'Entregado'), ('installed', 'Instalado'), ('cancelled', 'Cancelado')], max_length=15, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_update', 'Actualización de pedido'), ('order_delivered', 'Pedido entregado'), ('promotion', 'Promoción'), ('general', 'General')], default='general', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Enlace (opcional)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Etiqueta (Casa, Oficina, etc.)')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Nombre del destinatario')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección completa')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección de usuario',
                'verbose_name_plural': 'Direcciones de usuarios',
                'db_table': 'user_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ecommerce.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='uniq_favorite_user_product')],
            },
        ),
    ]
