"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
from .jwt_settings import SIMPLE_JWT
"""

from pathlib import Path
import os
import sys
import pymysql
from dotenv import load_dotenv
from decouple import config
import cloudinary
from datetime import timedelta
from urllib.parse import urlparse

pymysql.install_as_MySQLdb()

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Configurar Cloudinary desde CLOUDINARY_URL en .env
cloudinary_url = os.environ.get('CLOUDINARY_URL')
if cloudinary_url:
    cloudinary.config(cloudinary_url=cloudinary_url, secure=True)
else:
    cloudinary.config(secure=True)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

def _csv_env(name, default=''):
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


ALLOWED_HOSTS = _csv_env(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,backend,nginx',
)

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'usuarios',
    'ecommerce',
    'gestion',
    'crmChat',
    'AppVisits',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _csv_env(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost,http://localhost:81,http://localhost:3000,http://127.0.0.1,http://127.0.0.1:81,http://127.0.0.1:3000',
)
CSRF_TRUSTED_ORIGINS = _csv_env(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost,http://localhost:81,http://localhost:3000,http://127.0.0.1,http://127.0.0.1:81,http://127.0.0.1:3000',
)

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
    'idempotency-key',
    'if-match',
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'auth.authentication.PasswordVersionJWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('THROTTLE_ANON_RATE', default='60/min'),
        'user': config('THROTTLE_USER_RATE', default='300/min'),
        'login': config('THROTTLE_LOGIN_RATE', default='5/min'),
        'password_reset_request': config('THROTTLE_PASSWORD_RESET_REQUEST_RATE', default='5/min'),
        'password_reset_confirm': config('THROTTLE_PASSWORD_RESET_CONFIRM_RATE', default='10/min'),
        'chat': config('THROTTLE_CHAT_RATE', default='20/min'),
        'reviews': config('THROTTLE_REVIEW_RATE', default='30/min'),
        'payment_status': config('THROTTLE_PAYMENT_RATE', default='30/min'),
        'fcm': config('THROTTLE_FCM_RATE', default='30/min'),
        'wompi_webhook': config('THROTTLE_WOMPI_WEBHOOK_RATE', default='240/min'),
        'meta_webhook': config('THROTTLE_META_WEBHOOK_RATE', default='600/min'),
        'meta_admin': config('THROTTLE_META_ADMIN_RATE', default='20/min'),
    },
}

DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', default=25 * 1024 * 1024, cast=int)
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=5 * 1024 * 1024, cast=int)
DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', default=1000, cast=int)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [config('CHANNEL_REDIS_URL', default='redis://redis:6379/2')],
            'capacity': 1500,
            'expiry': 60,
        },
    },
}

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis:6379/0')
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = config('CELERY_TASK_TIME_LIMIT', default=120, cast=int)
CELERY_TASK_SOFT_TIME_LIMIT = config('CELERY_TASK_SOFT_TIME_LIMIT', default=110, cast=int)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = 'America/Bogota'
CELERY_BEAT_SCHEDULE = {
    'close-inactive-bot-sessions': {
        'task': 'crmChat.tasks.close_inactive_bot_sessions',
        'schedule': timedelta(seconds=30),
    },
    # Meta no tiene un mecanismo único de refresh para los tres productos. Se
    # auditan vencimientos y la rotación se realiza de forma segura en el panel.
    'audit-meta-token-expiration-daily': {
        'task': 'crmChat.tasks.audit_meta_tokens',
        'schedule': timedelta(hours=24),
    },
    'validate-meta-oauth-connections-daily': {
        'task': 'crmChat.tasks.validate_meta_oauth_connections',
        'schedule': timedelta(hours=24),
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_engine = os.getenv('DB_ENGINE', 'django.db.backends.mysql')

if 'sqlite3' in _db_engine:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    _db_options = {}
    if 'mysql' in _db_engine:
        _db_options = {'charset': os.getenv('DB_CHARSET', 'utf8mb4')}

    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DB_NAME', ''),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': _db_options,
        }
    }

# Las pruebas usan una base SQLite aislada. Nunca deben reutilizar ni borrar la
# base local de desarrollo que vive en BASE_DIR/db.sqlite3.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }

AUTH_USER_MODEL = 'usuarios.Credenciales'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files — uploaded images (products, brands, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration - Capacitaciones Generales (GoDaddy - Default)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@regencysa.net')
PASSWORD_RESET_TIMEOUT = 3600
CASH_ON_DELIVERY_ENABLED = config('CASH_ON_DELIVERY_ENABLED', default=False, cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

# Email Configuration - Exámenes Médicos (360 CloudRegency)
EMAIL_MEDICAL_HOST = config('EMAIL_MEDICAL_HOST', default='360.cloudregencyapps.com')
EMAIL_MEDICAL_PORT = config('EMAIL_MEDICAL_PORT', default=465, cast=int)
EMAIL_MEDICAL_USE_SSL = config('EMAIL_MEDICAL_USE_SSL', default=True, cast=bool)
EMAIL_MEDICAL_USE_TLS = config('EMAIL_MEDICAL_USE_TLS', default=False, cast=bool)
EMAIL_MEDICAL_HOST_USER = config('EMAIL_MEDICAL_HOST_USER', default='')
EMAIL_MEDICAL_HOST_PASSWORD = config('EMAIL_MEDICAL_HOST_PASSWORD', default='')
EMAIL_MEDICAL_FROM_EMAIL = config('EMAIL_MEDICAL_FROM_EMAIL', default='notificacionexamenes@360.cloudregencyapps.com')
EMAIL_MEDICAL_TIMEOUT = config('EMAIL_MEDICAL_TIMEOUT', default=30, cast=int)  # Usa el mismo timeout

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Ollama Chatbot Configuration
# En Docker usa 'ollama', en desarrollo local usa 'localhost'
OLLAMA_API_URL = config('OLLAMA_API_URL', default='http://ollama:11434/api/chat')
OLLAMA_MODEL = config('OLLAMA_MODEL', default='qwen:4b')
OLLAMA_TIMEOUT = config('OLLAMA_TIMEOUT', default=90, cast=int)
OLLAMA_NUM_CTX = config('OLLAMA_NUM_CTX', default=4096, cast=int)
OLLAMA_ECOMMERCE_ENABLED = config('OLLAMA_ECOMMERCE_ENABLED', default=True, cast=bool)

# Public URLs used in replies generated by the CRM.  Keep these absolute so
# links sent through external channels continue to work outside the browser.
FRONTEND_PUBLIC_URL = config('FRONTEND_PUBLIC_URL', default='http://localhost').rstrip('/')
PRODUCT_URL_TEMPLATE = config(
    'PRODUCT_URL_TEMPLATE',
    default=f'{FRONTEND_PUBLIC_URL}/producto/{{id}}',
)
EXTERNAL_PRODUCT_URL_TEMPLATE = config(
    'EXTERNAL_PRODUCT_URL_TEMPLATE',
    default=PRODUCT_URL_TEMPLATE,
)
if '{id}' not in PRODUCT_URL_TEMPLATE:
    raise ValueError('PRODUCT_URL_TEMPLATE debe incluir el marcador {id}.')
if '{id}' not in EXTERNAL_PRODUCT_URL_TEMPLATE:
    raise ValueError('EXTERNAL_PRODUCT_URL_TEMPLATE debe incluir el marcador {id}.')
_external_product_host = (urlparse(EXTERNAL_PRODUCT_URL_TEMPLATE).hostname or '').lower()
if (
    urlparse(EXTERNAL_PRODUCT_URL_TEMPLATE).scheme != 'https'
    or _external_product_host in {'localhost', '127.0.0.1', 'backend', 'frontend', 'nginx'}
    or _external_product_host.endswith(('.local', '.internal'))
):
    raise ValueError('EXTERNAL_PRODUCT_URL_TEMPLATE debe usar una URL pública HTTPS.')
_product_host = (urlparse(PRODUCT_URL_TEMPLATE).hostname or '').lower()
if not DEBUG and _product_host in {'localhost', '127.0.0.1', 'backend', 'frontend', 'nginx'}:
    raise ValueError('PRODUCT_URL_TEMPLATE no puede usar una URL local en producción.')

# Cache Configuration
# Usa cache en memoria para desarrollo, Redis para producción
import sys

if 'test' in sys.argv:
    # Para tests: cache en memoria
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
elif os.getenv('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ['REDIS_URL'],
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
                'SOCKET_CONNECT_TIMEOUT': 2,
                'SOCKET_TIMEOUT': 2,
            },
        }
    }
elif DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    # Producción: Redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"redis://{os.getenv('REDIS_HOST', 'localhost')}:6379/1",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PARSER_KWARGS': {'decode_responses': True},
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
            }
        }
    }

# Tiempos de cache específicos (en segundos)
CACHE_TTL_CAPACITACIONES_LIST = 60 * 5  # 5 minutos para lista de capacitaciones
CACHE_TTL_CAPACITACION_DETAIL = 60 * 10  # 10 minutos para detalle de capacitación
CACHE_TTL_MIS_CAPACITACIONES = 60 * 2  # 2 minutos para mis capacitaciones (cambia más frecuentemente)
CACHE_TTL_PROGRESO_EMPRESARIAL = 60 * 30  # 30 minutos para analítica empresarial (datos pesados)

# ─── Wompi Payment Gateway ────────────────────────────────────────────────────
WOMPI_PUBLIC_KEY = config('WOMPI_PUBLIC_KEY', default='')
WOMPI_PRIVATE_KEY = config('WOMPI_PRIVATE_KEY', default='')
WOMPI_EVENTS_SECRET = config('WOMPI_EVENTS_SECRET', default='')
WOMPI_INTEGRITY_SECRET = config('WOMPI_INTEGRITY_SECRET', default='')
WOMPI_API_URL = config(
    'WOMPI_API_URL',
    default='https://sandbox.wompi.co/v1' if WOMPI_PUBLIC_KEY.startswith('pub_test_') else 'https://production.wompi.co/v1',
)
WOMPI_HTTP_TIMEOUT = config('WOMPI_HTTP_TIMEOUT', default=10, cast=int)

# Firebase Admin (solo backend). Se admite un secret montado como archivo o
# variables individuales de la cuenta de servicio.
FIREBASE_CREDENTIALS_FILE = config('FIREBASE_CREDENTIALS_FILE', default='')
FIREBASE_PROJECT_ID = config('FIREBASE_PROJECT_ID', default='')
FIREBASE_CLIENT_EMAIL = config('FIREBASE_CLIENT_EMAIL', default='')
FIREBASE_PRIVATE_KEY = config('FIREBASE_PRIVATE_KEY', default='')

# Meta Graph API. Los secretos solo pertenecen al backend. La versión no tiene
# valor predeterminado para impedir que una versión obsoleta se use sin revisión.
META_GRAPH_API_URL = config('META_GRAPH_API_URL', default='https://graph.facebook.com')
META_GRAPH_API_VERSION = config('META_GRAPH_API_VERSION', default='')
META_APP_ID = config('META_APP_ID', default='')
META_HTTP_TIMEOUT = config('META_HTTP_TIMEOUT', default=15, cast=int)
META_WEBHOOK_MAX_BYTES = config('META_WEBHOOK_MAX_BYTES', default=2 * 1024 * 1024, cast=int)
CRM_ATTACHMENT_MAX_BYTES = config('CRM_ATTACHMENT_MAX_BYTES', default=25 * 1024 * 1024, cast=int)
CRM_ATTACHMENT_MAX_REDIRECTS = config('CRM_ATTACHMENT_MAX_REDIRECTS', default=3, cast=int)
CRM_ATTACHMENT_DELIVERY_TTL = config('CRM_ATTACHMENT_DELIVERY_TTL', default=300, cast=int)
META_WEBHOOK_VERIFY_TOKEN = config('META_WEBHOOK_VERIFY_TOKEN', default='')
META_WEBHOOK_VERIFY_TOKEN_INSTAGRAM = config('META_WEBHOOK_VERIFY_TOKEN_INSTAGRAM', default='')
META_WEBHOOK_VERIFY_TOKEN_FACEBOOK = config('META_WEBHOOK_VERIFY_TOKEN_FACEBOOK', default='')
META_WEBHOOK_VERIFY_TOKEN_WHATSAPP = config('META_WEBHOOK_VERIFY_TOKEN_WHATSAPP', default='')
META_APP_SECRET = config('META_APP_SECRET', default='')
META_CREDENTIALS_ENCRYPTION_KEY = config('META_CREDENTIALS_ENCRYPTION_KEY', default='')
META_TOKEN_WARNING_DAYS = config('META_TOKEN_WARNING_DAYS', default=7, cast=int)
META_REDIRECT_URI = config('META_REDIRECT_URI', default='')
META_PUBLIC_BASE_URL = config('META_PUBLIC_BASE_URL', default='').rstrip('/')
API_BASE_URL = config('API_BASE_URL', default='/api/').rstrip('/') + '/'
API_PUBLIC_URL = config(
    'API_PUBLIC_URL',
    default=f'{FRONTEND_PUBLIC_URL}/api/',
).rstrip('/') + '/'
META_FACEBOOK_WEBHOOK_URL = config(
    'META_FACEBOOK_WEBHOOK_URL',
    default=f'{META_PUBLIC_BASE_URL}/api/meta/facebook/webhook/' if META_PUBLIC_BASE_URL else '',
)
META_INSTAGRAM_WEBHOOK_URL = config(
    'META_INSTAGRAM_WEBHOOK_URL',
    default=f'{META_PUBLIC_BASE_URL}/api/meta/instagram/webhook/' if META_PUBLIC_BASE_URL else '',
)
META_WHATSAPP_WEBHOOK_URL = config(
    'META_WHATSAPP_WEBHOOK_URL',
    default=f'{META_PUBLIC_BASE_URL}/api/meta/whatsapp/webhook/' if META_PUBLIC_BASE_URL else '',
)
META_OAUTH_AUTHORIZE_URL = config('META_OAUTH_AUTHORIZE_URL', default='https://www.facebook.com')
META_OAUTH_STATE_MAX_AGE = config('META_OAUTH_STATE_MAX_AGE', default=600, cast=int)
META_OAUTH_SCOPES = config(
    'META_OAUTH_SCOPES',
    default=(
        'pages_show_list,pages_read_engagement,pages_manage_metadata,'
        'pages_messaging,instagram_basic,instagram_manage_messages'
    ),
)
META_OAUTH_FRONTEND_REDIRECT = config(
    'META_OAUTH_FRONTEND_REDIRECT',
    default='/admin/chat/integraciones',
)
META_WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID = config(
    'META_WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID', default='',
)
# Embedded Signup v4 evita depender de los flujos v2/v3 que Meta retira para
# nuevas altas. El backend sigue aceptando el payload de sesión de coexistencia.
META_WHATSAPP_EMBEDDED_SIGNUP_VERSION = config(
    'META_WHATSAPP_EMBEDDED_SIGNUP_VERSION', default='4',
)
META_WHATSAPP_EMBEDDED_SIGNUP_STATE_MAX_AGE = config(
    'META_WHATSAPP_EMBEDDED_SIGNUP_STATE_MAX_AGE', default=600, cast=int,
)
CRM_INTERNAL_SERVICE_TOKEN = config('CRM_INTERNAL_SERVICE_TOKEN', default='')
WHATSAPP_GATEWAY_URL = config('WHATSAPP_GATEWAY_URL', default='http://whatsapp-gateway:3001')
WHATSAPP_GATEWAY_CONNECTION_ID = config('WHATSAPP_GATEWAY_CONNECTION_ID', default='primary')
WHATSAPP_GATEWAY_MAX_MEDIA_BYTES = config('WHATSAPP_GATEWAY_MAX_MEDIA_BYTES', default=25 * 1024 * 1024, cast=int)
WHATSAPP_GATEWAY_REQUEST_MAX_AGE = config('WHATSAPP_GATEWAY_REQUEST_MAX_AGE', default=300, cast=int)
WHATSAPP_GATEWAY_BOT_ENABLED = config('WHATSAPP_GATEWAY_BOT_ENABLED', default=False, cast=bool)

# Daphne incluye la query string en sus líneas de acceso. Meta transmite el
# verify token por query, por lo que se sanitiza antes de escribir cualquier log.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'redact_webhook_secrets': {
            '()': 'core.logging_filters.RedactWebhookSecretsFilter',
        },
    },
    'handlers': {
        'safe_console': {
            'class': 'logging.StreamHandler',
            'filters': ['redact_webhook_secrets'],
        },
    },
    'loggers': {
        'daphne.server': {
            'handlers': ['safe_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['safe_console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Instagram Business Login. La URI debe coincidir literalmente con la
# registrada en Meta for Developers y apuntar al callback HTTPS de Django.
INSTAGRAM_OAUTH_REDIRECT_URI = config('INSTAGRAM_OAUTH_REDIRECT_URI', default='')
INSTAGRAM_OAUTH_AUTHORIZE_URL = config(
    'INSTAGRAM_OAUTH_AUTHORIZE_URL',
    default='https://www.instagram.com/oauth/authorize',
)
INSTAGRAM_OAUTH_TOKEN_URL = config(
    'INSTAGRAM_OAUTH_TOKEN_URL',
    default='https://api.instagram.com/oauth/access_token',
)
INSTAGRAM_GRAPH_API_URL = config('INSTAGRAM_GRAPH_API_URL', default='https://graph.instagram.com')
INSTAGRAM_OAUTH_SCOPES = config(
    'INSTAGRAM_OAUTH_SCOPES',
    default='instagram_business_basic,instagram_business_manage_messages',
)
INSTAGRAM_OAUTH_STATE_MAX_AGE = config('INSTAGRAM_OAUTH_STATE_MAX_AGE', default=600, cast=int)
