"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
from .jwt_settings import SIMPLE_JWT
"""

from pathlib import Path
import os
import sys
import pymysql
from dotenv import load_dotenv
from decouple import config
import cloudinary
from datetime import timedelta

pymysql.install_as_MySQLdb()

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Configurar Cloudinary desde CLOUDINARY_URL en .env
cloudinary_url = os.environ.get('CLOUDINARY_URL')
if cloudinary_url:
    cloudinary.config(cloudinary_url=cloudinary_url, secure=True)
else:
    cloudinary.config(secure=True)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

def _csv_env(name, default=''):
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


ALLOWED_HOSTS = _csv_env(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,0.0.0.0,testserver,.ngrok.io',
)

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'usuarios',
    'ecommerce',
    'gestion',
    'crmChat',
    'AppVisits',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _csv_env(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost,http://localhost:81,http://localhost:3000,http://127.0.0.1,http://127.0.0.1:81,http://127.0.0.1:3000',
)
CSRF_TRUSTED_ORIGINS = _csv_env(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost,http://localhost:81,http://localhost:3000,http://127.0.0.1,http://127.0.0.1:81,http://127.0.0.1:3000',
)

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('THROTTLE_ANON_RATE', default='60/min'),
        'user': config('THROTTLE_USER_RATE', default='300/min'),
        'login': config('THROTTLE_LOGIN_RATE', default='5/min'),
        'chat': config('THROTTLE_CHAT_RATE', default='20/min'),
        'reviews': config('THROTTLE_REVIEW_RATE', default='30/min'),
        'payment_status': config('THROTTLE_PAYMENT_RATE', default='30/min'),
        'fcm': config('THROTTLE_FCM_RATE', default='30/min'),
        'wompi_webhook': config('THROTTLE_WOMPI_WEBHOOK_RATE', default='240/min'),
    },
}

DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', default=25 * 1024 * 1024, cast=int)
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=5 * 1024 * 1024, cast=int)
DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', default=1000, cast=int)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_engine = os.getenv('DB_ENGINE', 'django.db.backends.mysql')

if 'sqlite3' in _db_engine:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    _db_options = {}
    if 'mysql' in _db_engine:
        _db_options = {'charset': os.getenv('DB_CHARSET', 'utf8mb4')}

    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DB_NAME', ''),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': _db_options,
        }
    }

# Para evitar errores de FK en MySQL durante las pruebas y acelerar el ciclo de test
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
        'TEST': {
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        },
    }

AUTH_USER_MODEL = 'usuarios.Credenciales'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files — uploaded images (products, brands, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration - Capacitaciones Generales (GoDaddy - Default)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@regencysa.net')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

# Email Configuration - Exámenes Médicos (360 CloudRegency)
EMAIL_MEDICAL_HOST = config('EMAIL_MEDICAL_HOST', default='360.cloudregencyapps.com')
EMAIL_MEDICAL_PORT = config('EMAIL_MEDICAL_PORT', default=465, cast=int)
EMAIL_MEDICAL_USE_SSL = config('EMAIL_MEDICAL_USE_SSL', default=True, cast=bool)
EMAIL_MEDICAL_USE_TLS = config('EMAIL_MEDICAL_USE_TLS', default=False, cast=bool)
EMAIL_MEDICAL_HOST_USER = config('EMAIL_MEDICAL_HOST_USER', default='')
EMAIL_MEDICAL_HOST_PASSWORD = config('EMAIL_MEDICAL_HOST_PASSWORD', default='')
EMAIL_MEDICAL_FROM_EMAIL = config('EMAIL_MEDICAL_FROM_EMAIL', default='notificacionexamenes@360.cloudregencyapps.com')
EMAIL_MEDICAL_TIMEOUT = config('EMAIL_MEDICAL_TIMEOUT', default=30, cast=int)  # Usa el mismo timeout

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Ollama Chatbot Configuration
# En Docker usa 'ollama', en desarrollo local usa 'localhost'
OLLAMA_API_URL = config('OLLAMA_API_URL', default='http://ollama:11434/api/chat')
OLLAMA_MODEL = config('OLLAMA_MODEL', default='qwen2.5:1.5b')
OLLAMA_TIMEOUT = config('OLLAMA_TIMEOUT', default=90, cast=int)
OLLAMA_NUM_CTX = config('OLLAMA_NUM_CTX', default=4096, cast=int)

# Cache Configuration
# Usa cache en memoria para desarrollo, Redis para producción
import sys

if 'test' in sys.argv:
    # Para tests: cache en memoria
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
elif os.getenv('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ['REDIS_URL'],
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
                'SOCKET_CONNECT_TIMEOUT': 2,
                'SOCKET_TIMEOUT': 2,
            },
        }
    }
elif DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    # Producción: Redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"redis://{os.getenv('REDIS_HOST', 'localhost')}:6379/1",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PARSER_KWARGS': {'decode_responses': True},
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
            }
        }
    }

# Tiempos de cache específicos (en segundos)
CACHE_TTL_CAPACITACIONES_LIST = 60 * 5  # 5 minutos para lista de capacitaciones
CACHE_TTL_CAPACITACION_DETAIL = 60 * 10  # 10 minutos para detalle de capacitación
CACHE_TTL_MIS_CAPACITACIONES = 60 * 2  # 2 minutos para mis capacitaciones (cambia más frecuentemente)
CACHE_TTL_PROGRESO_EMPRESARIAL = 60 * 30  # 30 minutos para analítica empresarial (datos pesados)

# ─── Wompi Payment Gateway ────────────────────────────────────────────────────
WOMPI_PUBLIC_KEY = config('WOMPI_PUBLIC_KEY', default='')
WOMPI_PRIVATE_KEY = config('WOMPI_PRIVATE_KEY', default='')
WOMPI_EVENTS_SECRET = config('WOMPI_EVENTS_SECRET', default='')
WOMPI_INTEGRITY_SECRET = config('WOMPI_INTEGRITY_SECRET', default='')
WOMPI_API_URL = config(
    'WOMPI_API_URL',
    default='https://sandbox.wompi.co/v1' if WOMPI_PUBLIC_KEY.startswith('pub_test_') else 'https://production.wompi.co/v1',
)
WOMPI_HTTP_TIMEOUT = config('WOMPI_HTTP_TIMEOUT', default=10, cast=int)

# Firebase Admin (solo backend). Se admite un secret montado como archivo o
# variables individuales de la cuenta de servicio.
FIREBASE_CREDENTIALS_FILE = config('FIREBASE_CREDENTIALS_FILE', default='')
FIREBASE_PROJECT_ID = config('FIREBASE_PROJECT_ID', default='')
FIREBASE_CLIENT_EMAIL = config('FIREBASE_CLIENT_EMAIL', default='')
FIREBASE_PRIVATE_KEY = config('FIREBASE_PRIVATE_KEY', default='')
