# Generated by Django 5.2.7 on 2026-08-03 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente de Visita',
                'verbose_name_plural': 'Clientes de Visita',
                'db_table': 'visita_cliente',
            },
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarea', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_tarea', models.CharField(choices=[('mantenimiento', 'Mantenimiento Preventivo'), ('instalacion', 'Instalación'), ('reparacion', 'Reparación'), ('revision', 'Revisión Técnica'), ('visita_tecnica', 'Visita Técnica Perímetro Urbano'), ('garantia', 'Garantía')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones_iniciales', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='AppVisits.clientevisita')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_creadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado')),
            ],
            options={
                'verbose_name': 'Visita Técnica',
                'verbose_name_plural': 'Visitas Técnicas',
                'db_table': 'visita_tecnica',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='ReporteVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_atiende', models.CharField(max_length=200)),
                ('equipo', models.CharField(choices=[('estufa', 'Estufa'), ('horno', 'Horno'), ('calentador', 'Calentador'), ('parrilla', 'Parrilla'), ('caldera', 'Caldera'), ('calefactor', 'Calefactor'), ('otro', 'Otro')], max_length=50)),
                ('equipo_otro', models.CharField(blank=True, max_length=100)),
                ('ubicacion_equipo', models.CharField(choices=[('cocina', 'Cocina'), ('patio', 'Patio'), ('balcon', 'Balcón'), ('exterior', 'Exterior'), ('sotano', 'Sótano'), ('otro', 'Otro')], max_length=50)),
                ('ubicacion_otro', models.CharField(blank=True, max_length=100)),
                ('motivo_servicio', models.TextField()),
                ('solucion_realizada', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('valor_servicio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito'), ('otro', 'Otro')], max_length=20)),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('inicio_desplazamiento', models.DateTimeField(blank=True, null=True)),
                ('duracion_desplazamiento', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='AppVisits.visitatecnica')),
            ],
            options={
                'verbose_name': 'Reporte de Visita',
                'verbose_name_plural': 'Reportes de Visita',
                'db_table': 'visita_reporte',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFotografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='AppVisits.visitatecnica')),
            ],
            options={
                'verbose_name': 'Evidencia Fotográfica',
                'verbose_name_plural': 'Evidencias Fotográficas',
                'db_table': 'visita_evidencia',
                'ordering': ['orden', 'subida_en'],
            },
        ),
    ]
