# Generated by Django 5.2.7 on 2026-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVisits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevisita',
            name='firma_base64',
            field=models.TextField(blank=True, help_text='Firma en formato base64', null=True),
        ),
    ]
