# Generated by Django 5.2.7 on 2026-09-10 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVisits', '0004_visitsyncreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitatecnica',
            name='valor_visita',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor monetario acordado para la visita técnica.', max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='visitatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('valor_visita__gte', 0), ('valor_visita__isnull', True), _connector='OR'), name='visita_valor_no_negativo'),
        ),
    ]
