# Generated by Django 5.2.7 on 2026-09-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


LEGACY_TYPES = (
    ('visita_urbana', 'VISITA TECNICA PERIMETRO URBANO'),
    ('instalacion_calentador', '2025 INSTALACION DE CALENTADOR'),
    ('mantenimiento_calentador', '2025 MANTENIMIENTO O REPARACION DE CALENTADOR'),
    ('instalacion_secadora', '2025 INSTALACION DE SECADORA'),
    ('servicio_cancelado', 'SERVICIO CANCELADO'),
    ('visita_afueras', 'VISITA TECNICA PERIMETRO URBANO AFUERAS'),
    ('mantenimiento_estufa', '2025 MANTENIMIENTO O REPARACION DE ESTUFA'),
    ('revision_periodica', 'REVISION PERIODICA'),
    ('mantenimiento_acumulacion', '2025 MANTENIMIENTO O REPARACION CALENTADOR DE ACUMULACION A GAS'),
    ('programacion_doble', 'PROGRAMACION DOBLE'),
    ('mantenimiento_turco', '2025 MANTENIMIENTO O REPARACION CALENTADOR DE TURCO DE PASO'),
)


def preserve_visit_types(apps, schema_editor):
    Visit = apps.get_model('AppVisits', 'VisitaTecnica')
    VisitType = apps.get_model('AppVisits', 'TipoVisita')
    labels = dict(LEGACY_TYPES)
    for code, label in LEGACY_TYPES:
        VisitType.objects.get_or_create(codigo=code, defaults={'nombre': label, 'activo': True})
    for code in Visit.objects.values_list('tipo_tarea', flat=True).distinct():
        if not code:
            continue
        label = labels.get(code, code)
        VisitType.objects.get_or_create(codigo=code, defaults={'nombre': label, 'activo': False})
        Visit.objects.filter(tipo_tarea=code, tipo_tarea_etiqueta='').update(tipo_tarea_etiqueta=label)


class Migration(migrations.Migration):

    dependencies = [
        ('AppVisits', '0006_visit_service_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visita_tipo',
                'ordering': ['nombre', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='clientevisita',
            name='indicaciones_llegada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='tipo_tarea_etiqueta',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='tipo_tarea',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CambioCostoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_costo', to='AppVisits.visitatecnica')),
            ],
            options={
                'db_table': 'visita_cambio_costo',
                'ordering': ['-cambiado_en'],
            },
        ),
        migrations.RunPython(preserve_visit_types, migrations.RunPython.noop),
    ]
