# Generated by Django 5.2.7 on 2026-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVisits', '0007_visit_types_directions_cost_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitatecnica',
            name='pdf_final',
            field=models.FileField(blank=True, null=True, upload_to='visitas_pdf/'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='whatsapp_notificacion_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='whatsapp_notificacion_estado',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
