# Generated by Django 5.2.7 on 2026-06-01 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0005_add_location_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Número')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre cliente')),
                ('cliente_cedula', models.CharField(blank=True, max_length=30, verbose_name='Cédula')),
                ('cliente_correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('convertida', 'Convertida a Factura')], default='borrador', max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal')),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %')),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento $')),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Impuesto %')),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Impuesto $')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ecommerce.location', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento_item', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento línea $')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Subtotal')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem cotización',
                'verbose_name_plural': 'Ítems cotización',
                'db_table': 'cotizacion_items',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Número')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre cliente')),
                ('cliente_cedula', models.CharField(blank=True, max_length=30, verbose_name='Cédula')),
                ('cliente_correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada')], default='emitida', max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='gestion.cotizacion', verbose_name='Cotización origen')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ecommerce.location', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento_item', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento línea $')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Subtotal')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem factura',
                'verbose_name_plural': 'Ítems factura',
                'db_table': 'factura_items',
            },
        ),
    ]
