# Generated by Django 5.2.7 on 2026-06-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente_correo',
            field=models.CharField(blank=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_correo',
            field=models.CharField(blank=True, max_length=254, verbose_name='Correo'),
        ),
    ]
