"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
from .jwt_settings import SIMPLE_JWT
"""

from pathlib import Path
import os
import sys
import pymysql
from dotenv import load_dotenv
from decouple import config
import cloudinary
from datetime import timedelta

pymysql.install_as_MySQLdb()

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Configurar Cloudinary desde CLOUDINARY_URL en .env
cloudinary_url = os.environ.get('CLOUDINARY_URL')
if cloudinary_url:
    cloudinary.config(cloudinary_url=cloudinary_url, secure=True)
else:
    cloudinary.config(secure=True)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '62.72.7.176',
    '.ngrok.io',
    'juvenescent-tamelessly-dennis.ngrok-free.dev',
    '127.0.0.1',
    'formacion.cloudregencyapps.com',
    'testserver',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'usuarios',
    'capacitaciones',
    'analitica',
    'evaluaciones',
    'examenes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', ''),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': os.getenv('DB_CHARSET', 'utf8mb4'),
        },
    }
}

# Para evitar errores de FK en MySQL durante las pruebas y acelerar el ciclo de test
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
        'TEST': {
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        },
    }

AUTH_USER_MODEL = 'usuarios.Usuarios'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

X_FRAME_OPTIONS = 'ALLOWALL'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration - Capacitaciones Generales (GoDaddy - Default)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@regencysa.net')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

# Email Configuration - Exámenes Médicos (360 CloudRegency)
EMAIL_MEDICAL_HOST = config('EMAIL_MEDICAL_HOST', default='360.cloudregencyapps.com')
EMAIL_MEDICAL_PORT = config('EMAIL_MEDICAL_PORT', default=465, cast=int)
EMAIL_MEDICAL_USE_SSL = config('EMAIL_MEDICAL_USE_SSL', default=True, cast=bool)
EMAIL_MEDICAL_USE_TLS = config('EMAIL_MEDICAL_USE_TLS', default=False, cast=bool)
EMAIL_MEDICAL_HOST_USER = config('EMAIL_MEDICAL_HOST_USER', default='')
EMAIL_MEDICAL_HOST_PASSWORD = config('EMAIL_MEDICAL_HOST_PASSWORD', default='')
EMAIL_MEDICAL_FROM_EMAIL = config('EMAIL_MEDICAL_FROM_EMAIL', default='notificacionexamenes@360.cloudregencyapps.com')
EMAIL_MEDICAL_TIMEOUT = config('EMAIL_MEDICAL_TIMEOUT', default=30, cast=int)  # Usa el mismo timeout


# Media files
# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default=str(os.path.join(BASE_DIR.parent, 'media')))

# Cache Configuration
# Usa cache en memoria para desarrollo, Redis para producción
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            "PASSWORD": "TU_PASSWORD",
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Tiempos de cache específicos (en segundos)
CACHE_TTL_CAPACITACIONES_LIST = 60 * 5  # 5 minutos para lista de capacitaciones
CACHE_TTL_CAPACITACION_DETAIL = 60 * 10  # 10 minutos para detalle de capacitación
CACHE_TTL_MIS_CAPACITACIONES = 60 * 2  # 2 minutos para mis capacitaciones (cambia más frecuentemente)
CACHE_TTL_PROGRESO_EMPRESARIAL = 60 * 30  # 30 minutos para analítica empresarial (datos pesados)
