# Generated by Django 5.2.7 on 2026-04-07 16:47

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecargo', models.CharField(max_length=30)),
                ('estadocargo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('idnivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombrenivel', models.CharField(max_length=50)),
                ('estadonivel', models.IntegerField(default=1)),
                ('prom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'niveles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('idregional', models.AutoField(primary_key=True, serialize=False)),
                ('nombreregional', models.CharField(max_length=30)),
                ('estadoregional', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'regional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('idcolaborador', models.AutoField(primary_key=True, serialize=False)),
                ('cccolaborador', models.CharField(blank=True, max_length=30, unique=True)),
                ('nombrecolaborador', models.CharField(max_length=30)),
                ('apellidocolaborador', models.CharField(max_length=30)),
                ('correocolaborador', models.CharField(blank=True, max_length=50, null=True)),
                ('telefocolaborador', models.CharField(blank=True, max_length=20, null=True)),
                ('estadocolaborador', models.IntegerField(default=1)),
                ('cargocolaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cargo')),
                ('nivelcolaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.niveles')),
                ('regionalcolab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.regional')),
            ],
            options={
                'db_table': 'colaboradores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('estadousuario', models.IntegerField(default=1)),
                ('tipousuario', models.IntegerField()),
                ('idcolaboradoru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.colaboradores')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
