# Generated by Django 5.2.7 on 2026-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
