# Generated by Django 5.2.7 on 2026-06-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_add_location_hours'),
        ('usuarios', '0003_usuario_credenciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciales',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='ecommerce.location', verbose_name='Sede asignada'),
        ),
    ]
