# Generated by Django 5.2.7 on 2026-09-04 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmChat', '0003_chatsession_conversation_memory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('auto_assign', models.BooleanField(default=False)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_assignment_queue',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'crm_queue_member',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('channel', models.CharField(choices=[('ecommerce', 'Ecommerce'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido')], db_index=True, default='received', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_webhook_event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente'), ('internal', 'Interno')], db_index=True, default='internal', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='external_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='external_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('sticker', 'Sticker'), ('template', 'Plantilla'), ('interactive', 'Interactivo')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to_external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('received', 'Recibido'), ('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], db_index=True, default='received', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram')], db_index=True, default='ecommerce', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='external_thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_agent_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_customer_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crmChat.assignmentqueue'),
        ),
        migrations.CreateModel(
            name='ChannelIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('ecommerce', 'Ecommerce'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('app_id', models.CharField(blank=True, max_length=120)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('phone_number_id', models.CharField(blank=True, max_length=120)),
                ('page_id', models.CharField(blank=True, max_length=120)),
                ('instagram_account_id', models.CharField(blank=True, max_length=120)),
                ('graph_api_version', models.CharField(blank=True, max_length=20)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('app_secret_encrypted', models.TextField(blank=True)),
                ('verify_token_digest', models.CharField(blank=True, max_length=64)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_channel_integration',
                'ordering': ['channel', 'name'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crmChat.channelintegration'),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='crm_chat/%Y/%m/')),
                ('external_media_id', models.CharField(blank=True, max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crmChat.chatmessage')),
            ],
            options={
                'db_table': 'crm_chat_attachment',
            },
        ),
        migrations.CreateModel(
            name='ChatAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_audit_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='crmChat.chatsession')),
            ],
            options={
                'db_table': 'crm_chat_audit_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cliente', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contact',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_identities', to='crmChat.channelintegration')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_identities', to='crmChat.crmcontact')),
            ],
            options={
                'db_table': 'crm_channel_identity',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crmChat.crmcontact'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['channel', 'status', '-updated_at'], name='crm_session_channel_status'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['queue', 'priority', '-updated_at'], name='crm_session_queue_priority'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('external_thread_id', ''), _negated=True), fields=('integration', 'external_thread_id'), name='crm_unique_external_thread'),
        ),
        migrations.AddField(
            model_name='queuemember',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crmChat.assignmentqueue'),
        ),
        migrations.AddField(
            model_name='queuemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_queue_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='crmChat.channelintegration'),
        ),
        migrations.AddConstraint(
            model_name='channelintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('external_account_id', ''), _negated=True), fields=('channel', 'external_account_id'), name='crm_unique_channel_external_account'),
        ),
        migrations.AddConstraint(
            model_name='channelidentity',
            constraint=models.UniqueConstraint(fields=('integration', 'external_id'), name='crm_unique_integration_identity'),
        ),
        migrations.AddConstraint(
            model_name='queuemember',
            constraint=models.UniqueConstraint(fields=('queue', 'user'), name='crm_unique_queue_member'),
        ),
    ]
