# Generated by Django 5.2.7 on 2026-09-11 19:57

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmChat', '0004_assignmentqueue_queuemember_webhookevent_and_more'),
        # Credenciales se creó en 0003; depender solo de __first__ deja el
        # estado histórico sin AUTH_USER_MODEL al ejecutar sqlmigrate desde cero.
        ('usuarios', '0004_credenciales_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_id', models.CharField(max_length=120)),
                ('access_token_encrypted', models.TextField()),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('token_created_at', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('token_status', models.CharField(choices=[('pending', 'Pendiente de selección'), ('valid', 'Válido'), ('expired', 'Expirado'), ('revoked', 'Revocado'), ('error', 'Error')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_meta_connection',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='meta_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_integrations', to='crmChat.metaconnection'),
        ),
        migrations.CreateModel(
            name='MetaFacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=120, unique=True)),
                ('page_name', models.CharField(max_length=200)),
                ('page_access_token_encrypted', models.TextField()),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to='crmChat.metaconnection')),
            ],
            options={
                'db_table': 'crm_meta_facebook_page',
                'ordering': ['page_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='meta_facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_integrations', to='crmChat.metafacebookpage'),
        ),
        migrations.CreateModel(
            name='MetaInstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account_id', models.CharField(max_length=120, unique=True)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('profile_picture_url', models.URLField(blank=True, max_length=1000)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_account', to='crmChat.metafacebookpage')),
            ],
            options={
                'db_table': 'crm_meta_instagram_account',
                'ordering': ['username', 'id'],
            },
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='meta_instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_integrations', to='crmChat.metainstagramaccount'),
        ),
        migrations.AddConstraint(
            model_name='metaconnection',
            constraint=models.UniqueConstraint(fields=('created_by', 'facebook_user_id'), name='crm_unique_meta_user_connection'),
        ),
    ]
