# Generated by Django 5.2.7 on 2026-09-16 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmChat', '0008_repair_whatsapp_protected_user_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatsession',
            name='crm_unique_external_thread',
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_thread_id', ''), _negated=True), models.Q(('status', 'closed'), _negated=True)), fields=('integration', 'external_thread_id'), name='crm_unique_active_external_thread'),
        ),
    ]
