# Generated by Django 5.2.7 on 2026-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmChat', '0009_active_external_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelintegration',
            name='business_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='connection_status',
            field=models.CharField(choices=[('pending', 'Pendiente de validar'), ('connected', 'Conectada y validada'), ('error', 'Error de validación'), ('disconnected', 'Desconectada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='display_phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelintegration',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
