# Generated by Django 5.2.7 on 2026-09-18 18:17

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def deactivate_conflicting_accounts(apps, schema_editor):
    """Conserva registros e historial y deja activa una sola cuenta por ID real."""
    Integration = apps.get_model('crmChat', 'ChannelIntegration')
    for channel, field in (
        ('whatsapp', 'phone_number_id'),
        ('facebook', 'page_id'),
        ('instagram', 'instagram_account_id'),
    ):
        conflicting = (
            Integration.objects.using(schema_editor.connection.alias)
            .filter(channel=channel, active=True)
            .exclude(**{field: ''})
            .values(field)
            .annotate(total=Count('pk'))
            .filter(total__gt=1)
        )
        for conflict in conflicting:
            ids = list(
                Integration.objects.using(schema_editor.connection.alias)
                .filter(channel=channel, active=True, **{field: conflict[field]})
                .order_by('-last_validated_at', '-updated_at', '-pk')
                .values_list('pk', flat=True)
            )
            Integration.objects.using(schema_editor.connection.alias).filter(pk__in=ids[1:]).update(
                active=False,
                connection_status='error',
                last_error='Desactivada por conflicto de identificador externo durante la migración.',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('crmChat', '0010_channelintegration_business_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deactivate_conflicting_accounts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='channelintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('channel', 'whatsapp'), models.Q(('phone_number_id', ''), _negated=True)), fields=('phone_number_id',), name='crm_unique_active_whatsapp_phone'),
        ),
        migrations.AddConstraint(
            model_name='channelintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('channel', 'facebook'), models.Q(('page_id', ''), _negated=True)), fields=('page_id',), name='crm_unique_active_facebook_page'),
        ),
        migrations.AddConstraint(
            model_name='channelintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('channel', 'instagram'), models.Q(('instagram_account_id', ''), _negated=True)), fields=('instagram_account_id',), name='crm_unique_active_instagram_account'),
        ),
    ]
