# Generated by Django 5.2.7 on 2026-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmChat', '0011_channelintegration_crm_unique_active_whatsapp_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelintegration',
            name='channel',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('whatsapp', 'WhatsApp'), ('whatsapp_web', 'WhatsApp Web experimental'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('whatsapp', 'WhatsApp'), ('whatsapp_web', 'WhatsApp Web experimental'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram')], db_index=True, default='ecommerce', max_length=20),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='channel',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('whatsapp', 'WhatsApp'), ('whatsapp_web', 'WhatsApp Web experimental'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram')], max_length=20),
        ),
    ]
